apiVersion: v1
kind: Service
metadata:
  name: wordpress
  labels:
    app: wordpress
spec:
  ports:
    - port: 80
  selector:
    app: wordpress
    tier: frontend
  type: LoadBalancer
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mywordpresspvc1
  labels:
    app: wordpress
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: apps/v1
kind: Deployment

metadata:
  name: "rswordpress"

spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend

  template:
    metadata:
      name: "mywordpress"
      labels:
        app: wordpress
        tier: frontend

    spec:
      containers:
      - name: "mywordpresscon1"
        image: "wordpress:4.8-apache"
        env:
        - name: wordpress_DB_HOST
          value: wordpressmysql
        - name: wordpress_DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mydbsecret
              key: rootpass
        ports:
        - containerPort: 80
          name: wordpress
        volumeMounts:
          - name: wordpress-vol1
            mountPath: /var/www/html
      volumes:
        - name: wordpress-vol1
          persistentVolumeClaim:
            claimName: mywordpresspvc1